# Generated by Django 5.2.17 on 2026-09-14 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('game', 'Roblox Game'), ('web', 'Web'), ('desktop', 'Windows App'), ('mobile', 'Mobile App'), ('tool', 'Desktop Tool')], default='web', max_length=20)),
                ('cover', models.CharField(max_length=255)),
                ('cover_alt', models.CharField(max_length=255)),
                ('tech_stack', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
