# Generated by Django 5.2.17 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
