# Generated by Django 5.2.17 on 2026-09-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_project_image_url_project_project_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
